apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          securityContext:
            privileged: true
            runAsUser: 0 
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: AWS_SECRET_KEY
              value: "hardcoded-secret"
      hostNetwork: true
      automountServiceAccountToken: true 
